version: '3'
services:
  #db:
    #image: mysql
    #volumes:
      #- ./db/mysql:/docker-entrypoint-initdb.d
    #environment:
      #MYSQL_ROOT_PASSWORD: '123qwe'
      #MYSQL_DATABASE: 'urlshortener'
      #MYSQL_USER: 'urlshortener'
      #MYSQL_PASSWORD: 'urlshortener'

  db:
    image: postgres
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 'urlshortener'
      POSTGRES_USER: 'urlshortener'
      POSTGRES_DB: 'urlshortener'

  web:
    image: node:8
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE: postgres
    working_dir: /usr/src/app
    command: yarn watch